dist: trusty
sudo: required
language: cpp

before_install:
 - sudo apt-get install -y -qq git build-essential libglib2.0-dev openjdk-6-jdk python-dev cmake gtk-doc-tools libgtkmm-2.4-dev  freeglut3-dev libjpeg-dev libtinyxml-dev libboost-thread-dev libgtk2.0-dev python-gtk2 mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libqwt-dev

script:
 - make -v
 - gcc -v
 - g++ -v
 - cmake -v
 - VERBOSE=1 make

